server:
  port: 8081  # Port for the Medical History Service

spring:
  application:
    name: medical-history-service  # This name is registered in Eureka

  datasource:
    url: jdbc:mysql://localhost:3306/medical_db?createDatabaseIfNotExist=true  # Replace with your DB details
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for dev, 'validate' for production
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect  # Set dialect for MySQL

  cloud:
    discovery:
      enabled: true
      service-id: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL of your Eureka server
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info  # Expose health and info endpoints for Actuator
